# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joseph Sintum's Blog
email: joseph24jay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Notes on building software and robots.
  Scripted with love by Joseph Sintum.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://josephsintum.github.io" # the base hostname & protocol for your site
twitter_username: josephsintum
github_username:  josephsintum

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman    