# REMEMBER TO GO THROUGH THIS FILE, PERSONALISING THE SETTINGS

title: Jay's Notes
author:
  name: Joseph Sintum
  github: josephsintum
  twitter: josephsintum

# If you don't have a favicon, change to false.
favicon: false

footer:
  separator: '|'
  content: Ⓒ Joseph Sintum Here
  # Append current year on build
  year: true

baseurl: "" # Use if your site will be located in a subdirectory, e.g. /blog.
url: "https://josephsintum.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

description: Your site description.

# Build settings
markdown: kramdown
theme: fundamental


# Enable theme compononents
enabled:
  breadcrumbs: true
  tags: true
  comments: true
  # Enable RSS menu item
  rss: false
  seo: true
  # Share buttons are only on desktop (user use the share menu on mobile).
  social:
    enabled: true
    twitter: true
    facebook: false
    messenger: false
    whatsapp: true

# Get your disquas shortname from the disqus admin panel for your blog.
disqus_shortname: your-forum-shortname
# Define the colors for social buttons.
socialBtnsColor: '#4845DF'

bio:
  enabled: true
  animate: true
  heading: This is Joseph Sintum
  subheading: 'Your subheading'
  img_url: false # 'your-img-url'
  body: >
    Hello, I'm a software developer in California...
#Plugins
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-seo-tag
  - jekyll-paginate

# Compress Sass for production.
sass:
  style: compressed

# Specifying front matter defaults
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: posts
    values:
      layout: "post"
      author: "Joseph Sintum"
      comments: true


permalink: pretty

#######
#PLUGIN CONFIG
#######

# Archives
jekyll-archives:
  enabled:
  - year
  - month
  - tags
  layout: 'archive'
  layouts:
    tag: 'tag_page'
    month: month
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'

paginate: 20